import "./WebsitePreview.css";
import JSZip from "jszip";

function WebsitePreview({
  businessData,
  websiteContent,
  template = "modern",
  onBack,
}) {
  const businessName =
    businessData.business_name || "Your Business";

  const category =
    businessData.category || "Business";

  const location =
    businessData.location || "Your Location";

  const products =
    businessData.products || [];

  // --------------------------------
  // AI Generated Content
  // --------------------------------

  const heroTitle =
    websiteContent?.hero_title ||
    `Welcome to ${businessName}`;

  const heroDescription =
    websiteContent?.hero_description ||
    `Your trusted ${category} in ${location}.`;

  const aboutText =
    websiteContent?.about ||
    `Welcome to ${businessName}. We are proud to serve customers in ${location}.`;

  const services =
    websiteContent?.services?.length > 0
      ? websiteContent.services
      : products.map((product) => ({
          name: product,
          description:
            `Professional ${product} services for our customers.`,
        }));

  const cta =
    websiteContent?.cta ||
    "Contact Us";


  // --------------------------------
  // Download Website
  // --------------------------------

  const downloadWebsite = async () => {
    try {
      const preview =
        document.querySelector(
          ".website-preview"
        );

      if (!preview) {
        alert(
          "Could not find the website preview."
        );
        return;
      }

      // Clone the preview
      const clonedPreview =
        preview.cloneNode(true);

      // Remove MakeSite-only buttons
      const backButton =
        clonedPreview.querySelector(
          ".back-button"
        );

      if (backButton) {
        backButton.remove();
      }

      const downloadButton =
        clonedPreview.querySelector(
          ".download-button"
        );

      if (downloadButton) {
        downloadButton.remove();
      }

      // --------------------------------
      // Collect CSS used by the preview
      // --------------------------------

      let css = "";

      for (
        const stylesheet of document.styleSheets
      ) {
        try {
          const rules =
            stylesheet.cssRules;

          if (!rules) {
            continue;
          }

          for (
            const rule of rules
          ) {
            css +=
              rule.cssText + "\n";
          }

        } catch (error) {
          console.warn(
            "Could not read stylesheet:",
            error
          );
        }
      }


      // --------------------------------
      // Create standalone HTML
      // --------------------------------

      const html = `
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="UTF-8">

  <meta
    name="viewport"
    content="width=device-width, initial-scale=1.0"
  >

  <title>${escapeHtml(
    businessName
  )}</title>

  <style>

${css}

  </style>

</head>

<body>

${clonedPreview.outerHTML}

</body>

</html>
`;


      // --------------------------------
      // Create ZIP
      // --------------------------------

      const zip = new JSZip();

      zip.file(
        "index.html",
        html
      );


      // Add a README file
      zip.file(
        "README.txt",
        `Website generated by MakeSite.

Business:
${businessName}

Template:
${template}

To open the website:
1. Extract this ZIP file.
2. Open index.html in your browser.

Generated by MakeSite.
`
      );


      // --------------------------------
      // Generate ZIP
      // --------------------------------

      const blob =
        await zip.generateAsync({
          type: "blob",
        });


      // --------------------------------
      // Download ZIP
      // --------------------------------

      const url =
        URL.createObjectURL(blob);

      const link =
        document.createElement("a");

      link.href = url;

      link.download =
        `${createSafeFileName(
          businessName
        )}-website.zip`;

      document.body.appendChild(link);

      link.click();

      document.body.removeChild(link);

      URL.revokeObjectURL(url);

    } catch (error) {

      console.error(
        "Website download error:",
        error
      );

      alert(
        "Could not download the website. Please try again."
      );

    }
  };


  // --------------------------------
  // Modern Template
  // --------------------------------

  if (template === "modern") {

    return (

      <div className="website-preview modern-template">

        <nav className="website-nav">

          <h2>
            {businessName}
          </h2>

          <div className="nav-links">

            <span>Home</span>

            <span>About</span>

            <span>Services</span>

            <span>Contact</span>

          </div>

        </nav>


        <section className="hero-section">

          <p className="category">
            {category}
          </p>

          <h1>
            {heroTitle}
          </h1>

          <p className="hero-text">
            {heroDescription}
          </p>

          {businessData.contact && (

            <button
              className="contact-button"
              onClick={() =>
                handleContact(
                  businessData.contact
                )
              }
            >
              {cta}
            </button>

          )}

        </section>


        <section className="about-section">

          <h2>
            About Us
          </h2>

          <p>
            {aboutText}
          </p>

        </section>


        {services.length > 0 && (

          <section className="services-section">

            <h2>
              Our Services
            </h2>

            <div className="services-grid">

              {services.map(
                (service, index) => (

                  <div
                    className="service-card"
                    key={index}
                  >

                    <h3>
                      {service.name}
                    </h3>

                    <p>
                      {service.description}
                    </p>

                  </div>

                )
              )}

            </div>

          </section>

        )}


        <ContactSection
          businessData={businessData}
        />


        <Footer
          businessName={businessName}
        />


        <DownloadButton
          onDownload={
            downloadWebsite
          }
        />


        <BackButton
          onBack={onBack}
        />

      </div>

    );

  }


  // --------------------------------
  // Minimal Template
  // --------------------------------

  if (template === "minimal") {

    return (

      <div className="website-preview minimal-template">

        <nav className="minimal-nav">

          <h2>
            {businessName}
          </h2>

          <div>

            <span>About</span>

            <span>Services</span>

            <span>Contact</span>

          </div>

        </nav>


        <section className="minimal-hero">

          <p>
            {category}
          </p>

          <h1>
            {heroTitle}
          </h1>

          <div className="minimal-line"></div>

          <p>
            {heroDescription}
          </p>

        </section>


        <section className="minimal-about">

          <h2>
            About
          </h2>

          <p>
            {aboutText}
          </p>

        </section>


        {services.length > 0 && (

          <section className="minimal-services">

            <h2>
              What We Offer
            </h2>

            <div className="minimal-service-list">

              {services.map(
                (service, index) => (

                  <div
                    className="minimal-service"
                    key={index}
                  >

                    <span>
                      {String(
                        index + 1
                      ).padStart(
                        2,
                        "0"
                      )}
                    </span>

                    <div>

                      <h3>
                        {service.name}
                      </h3>

                      <p>
                        {service.description}
                      </p>

                    </div>

                  </div>

                )
              )}

            </div>

          </section>

        )}


        <section className="minimal-contact">

          <h2>
            {cta}
          </h2>

          <p>
            {location}
          </p>

          {businessData.hours && (

            <p>
              {businessData.hours}
            </p>

          )}

          {businessData.contact && (

            <p>
              {businessData.contact}
            </p>

          )}

        </section>


        <footer className="minimal-footer">

          © 2026 {businessName}

        </footer>


        <DownloadButton
          onDownload={
            downloadWebsite
          }
        />


        <BackButton
          onBack={onBack}
        />

      </div>

    );

  }


  // --------------------------------
  // Bold Template
  // --------------------------------

  if (template === "bold") {

    return (

      <div className="website-preview bold-template">

        <nav className="bold-nav">

          <h2>
            {businessName}
          </h2>

          <div>

            <span>Home</span>

            <span>Services</span>

            <span>Contact</span>

          </div>

        </nav>


        <section className="bold-hero">

          <div className="bold-category">
            {category}
          </div>


          <h1>
            {heroTitle}
          </h1>


          <p>
            {heroDescription}
          </p>


          {businessData.contact && (

            <button
              className="bold-button"
              onClick={() =>
                handleContact(
                  businessData.contact
                )
              }
            >
              {cta} →
            </button>

          )}

        </section>


        <section className="bold-about">

          <div className="bold-number">
            01
          </div>


          <div>

            <h2>
              About {businessName}
            </h2>

            <p>
              {aboutText}
            </p>

          </div>

        </section>


        {services.length > 0 && (

          <section className="bold-services">

            <div className="bold-section-title">

              <span>
                02
              </span>

              <h2>
                OUR SERVICES
              </h2>

            </div>


            <div className="bold-service-grid">

              {services.map(
                (service, index) => (

                  <div
                    className="bold-service-card"
                    key={index}
                  >

                    <span>
                      {String(
                        index + 1
                      ).padStart(
                        2,
                        "0"
                      )}
                    </span>


                    <h3>
                      {service.name}
                    </h3>


                    <p>
                      {service.description}
                    </p>

                  </div>

                )
              )}

            </div>

          </section>

        )}


        <section className="bold-contact">

          <div className="bold-section-title">

            <span>
              03
            </span>

            <h2>
              CONTACT
            </h2>

          </div>


          <div className="bold-contact-info">

            <p>

              <strong>
                Location
              </strong>

              {location}

            </p>


            {businessData.hours && (

              <p>

                <strong>
                  Hours
                </strong>

                {businessData.hours}

              </p>

            )}


            {businessData.contact && (

              <p>

                <strong>
                  Contact
                </strong>

                {businessData.contact}

              </p>

            )}

          </div>

        </section>


        <footer className="bold-footer">

          <h2>
            {businessName}
          </h2>

          <p>
            © 2026 All rights reserved.
          </p>

        </footer>


        <DownloadButton
          onDownload={
            downloadWebsite
          }
        />


        <BackButton
          onBack={onBack}
        />

      </div>

    );

  }


  return null;
}


// --------------------------------
// Contact Section
// --------------------------------

function ContactSection({
  businessData,
}) {

  return (

    <section className="contact-section">

      <h2>
        Visit or Contact Us
      </h2>


      <div className="contact-info">

        <p>
          📍{" "}
          {businessData.location ||
            "Location not provided"}
        </p>


        {businessData.hours && (

          <p>
            🕒{" "}
            {businessData.hours}
          </p>

        )}


        {businessData.contact && (

          <p>
            📞{" "}
            {businessData.contact}
          </p>

        )}

      </div>

    </section>

  );
}


// --------------------------------
// Footer
// --------------------------------

function Footer({
  businessName,
}) {

  return (

    <footer className="website-footer">

      <p>
        © 2026 {businessName}
      </p>

    </footer>

  );

}


// --------------------------------
// Download Button
// --------------------------------

function DownloadButton({
  onDownload,
}) {

  return (

    <button
      className="download-button"
      onClick={onDownload}
    >
      ↓ Download Website
    </button>

  );

}


// --------------------------------
// Back Button
// --------------------------------

function BackButton({
  onBack,
}) {

  return (

    <button
      className="back-button"
      onClick={onBack}
    >
      ← Back
    </button>

  );

}


// --------------------------------
// Contact Handler
// --------------------------------

function handleContact(
  contact
) {

  if (!contact) {
    return;
  }

  const cleaned =
    String(contact)
      .replace(
        /[^0-9+@.]/g,
        ""
      );

  if (
    String(contact).includes("@")
  ) {

    window.location.href =
      `mailto:${contact}`;

  } else if (
    cleaned.length >= 7
  ) {

    window.location.href =
      `tel:${cleaned}`;

  }

}


// --------------------------------
// Escape HTML
// --------------------------------

function escapeHtml(
  value
) {

  return String(value)
    .replace(
      /&/g,
      "&amp;"
    )
    .replace(
      /</g,
      "&lt;"
    )
    .replace(
      />/g,
      "&gt;"
    )
    .replace(
      /"/g,
      "&quot;"
    )
    .replace(
      /'/g,
      "&#039;"
    );

}


// --------------------------------
// Safe filename
// --------------------------------

function createSafeFileName(
  value
) {

  return String(value)
    .trim()
    .replace(
      /[^a-zA-Z0-9-_ ]/g,
      ""
    )
    .replace(
      /\s+/g,
      "-"
    )
    .toLowerCase();

}


export default WebsitePreview;